pipeline:
  name: remotechained
  identifier: remotechained
  projectIdentifier: CSETest1
  orgIdentifier: AbhiOrg
  tags: {}
  stages:
    - stage:
        name: test2
        identifier: test2
        description: ""
        type: Pipeline
        spec:
          org: AbhiOrg
          pipeline: kartest
          project: CSETest1
          inputs:
            identifier: kartest
            stages:
              - stage:
                  identifier: test12
                  template:
                    templateInputs:
                      type: Custom
                      spec:
                        execution:
                          steps:
                            - step:
                                identifier: ShellScript_1
                                type: ShellScript
                                spec:
                                  environmentVariables:
                                    - name: test
                                      type: String
                                      value: <+input>
                                    - name: test2
                                      type: String
                                      value: <+input>
