pipeline:
  name: remotechained
  identifier: remotechained
  projectIdentifier: CSETest1
  orgIdentifier: AbhiOrg
  tags: {}
  stages:
    - stage:
        name: test2
        identifier: test2
        description: ""
        type: Pipeline
        spec:
          org: AbhiOrg
          pipeline: kartest
          project: CSETest1
          inputs:
            identifier: kartest
            stages:
              - stage:
                  identifier: test12
                  template:
                    templateInputs:
                      type: Custom
                      spec:
                        execution:
                          steps:
                            - step:
                                identifier: ShellScript_1
                                type: ShellScript
                                spec:
                                  environmentVariables:
                                    - name: test
                                      type: String
                                      value: <+input>
                                    - name: test2
                                      type: String
                                      value: <+input>
    - stage:
        name: test12
        identifier: test12
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo v
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
